# FuturX Agent Workspace - Production Docker Compose
# Version: v0.060
#
# 使用说明：
# 1. 创建目录: mkdir -p futurx-agent-workspace && cd futurx-agent-workspace
# 2. 下载此文件: wget https://raw.githubusercontent.com/futur-x/futurx_agent_workspace/main/docker-compose.production.yml
# 3. 创建.env文件并配置环境变量
# 4. 启动服务: docker-compose -f docker-compose.production.yml up -d

services:
  backend:
    image: elttilz/futurx-agent-backend:v0.060
    container_name: faw-backend
    ports:
      - "6173:6173"
    environment:
      - NODE_ENV=production
      - PORT=6173
      - DATABASE_URL=file:/app/data/faw.db
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_EXPIRY=${SESSION_EXPIRY:-30m}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    networks:
      - faw-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:6173/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: elttilz/futurx-agent-frontend:v0.060
    container_name: faw-frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - faw-network
    restart: unless-stopped
    # 如果后端不在同一个docker-compose网络中，需要添加extra_hosts
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

networks:
  faw-network:
    driver: bridge
    name: futurx-agent-network

volumes:
  data:
    name: faw-data
  uploads:
    name: faw-uploads