services:
  backend:
    build:
      context: ../
      dockerfile: docker_deploy/backend.Dockerfile
    container_name: faw-backend
    ports:
      - "6173:6173"
    environment:
      - NODE_ENV=production
      - PORT=6173
      - DATABASE_URL=file:/app/data/faw.db
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - SESSION_EXPIRY=30m
      - MAX_FILE_SIZE=10485760
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    networks:
      - faw-network
    restart: unless-stopped

  frontend:
    build:
      context: ../
      dockerfile: docker_deploy/frontend.Dockerfile
    container_name: faw-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - faw-network
    restart: unless-stopped

networks:
  faw-network:
    driver: bridge

volumes:
  data:
  uploads: